name: 'Deploy'
 
on:
  push:
    branches:
    - master
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  terraform:
    name: 'Deploy infrastructure'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      TF_VAR_appId: ${{ secrets.AZURE_AD_CLIENT_ID }}
      TF_VAR_password: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      TF_ACTIONS_WORKING_DIR: "./terraform"
      FLUX_GITHUB_USER: "tuxpeople"
      FLUX_GITHUB_REPO: "automationdemo-kubernetes"
      FLUX_GITHUB_BRANCH: "master"
      FLUX_GITHUB_PATH: "./clusters/demo"
      FLUX_GITHUB_KEY: "/home/runner/id_rsa_github"

    runs-on: ubuntu-latest
    environment: demo
 
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
 
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
      with:
         terraform_wrapper: false

    - name: Terraform fmt
      id: fmt
      working-directory: ${{ env.TF_ACTIONS_WORKING_DIR }}
      run: terraform fmt -check

    - name: Terraform Init
      id: init
      working-directory: ${{ env.TF_ACTIONS_WORKING_DIR }}
      run: terraform init

    - name: Terraform Validate
      id: validate
      working-directory: ${{ env.TF_ACTIONS_WORKING_DIR }}
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      working-directory: ${{ env.TF_ACTIONS_WORKING_DIR }}
      run: terraform plan -no-color -out=tfplan
 
    - name: Terraform Apply
      if: github.ref == 'refs/heads/master'
      id: apply
      working-directory: ${{ env.TF_ACTIONS_WORKING_DIR }}
      run: terraform apply -no-color tfplan

    - name: Login to azure
      uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
      with:
        creds: ${{ secrets.AZURE_CREDENTIAL }}

    - name: Get kubeconfig
      if: github.ref == 'refs/heads/master'
      id: kubeconfig
      working-directory: ${{ env.TF_ACTIONS_WORKING_DIR }}
      run: az aks get-credentials --resource-group $(terraform output -raw resource_group_name) --name $(terraform output -raw kubernetes_cluster_name)

    - name: Setup Flux CLI
      if: github.ref == 'refs/heads/master'
      id: install_flux
      uses: fluxcd/flux2/action@main
    
    - name: Bootstrap Flux
      if: github.ref == 'refs/heads/master'
      id: bootstrap_flux
      run: |
        GITHUB_TOKEN=${{ secrets.GH_TOKEN }} \
          flux bootstrap github  \
          --owner=${{ env.FLUX_GITHUB_USER }}  \
          --repository=${{ env.FLUX_GITHUB_REPO }}  \
          --branch=${{ env.FLUX_GITHUB_BRANCH }}  \
          --personal=true  \
          --private=false \
          --path=${{ env.FLUX_GITHUB_PATH }}