name: 'Destroy'
 
on: 
  workflow_dispatch:

jobs:
  terraform:
    name: 'Destroy infrastructure'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      TF_VAR_appId: ${{ secrets.AZURE_AD_CLIENT_ID }}
      TF_VAR_password: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      TF_ACTIONS_WORKING_DIR: "./terraform"

    runs-on: ubuntu-latest
    environment: demo
 
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
 
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - uses: hashicorp/setup-terraform@651471c36a6092792c552e8b1bef71e592b462d8 # v3.1.1

    - name: Terraform Init
      id: init
      working-directory: ${{ env.TF_ACTIONS_WORKING_DIR }}
      run: terraform init

    - name: Terraform Destroy
      id: destroy
      working-directory: ${{ env.TF_ACTIONS_WORKING_DIR }}
      run: terraform apply -destroy -no-color -auto-approve -lock=false